#!/bin/bash

DOCKER_IMAGE=devops/composer:1.10.1

source "$(dirname "$(realpath "$0")")"/rundocker

composer () {
    CACHE_FOLDER=~/.composer

    if [[ ! -d $CACHE_FOLDER ]]; then
        mkdir -p $CACHE_FOLDER/cache;
    fi

    extra_volumes="--volume $CACHE_FOLDER:/composer_cache" rundocker  "$@" --verbose --prefer-source --ignore-platform-reqs
}

composer2 () {
    CACHE_FOLDER=~/.composer

    if [[ ! -d $CACHE_FOLDER ]]; then
        mkdir -p $CACHE_FOLDER/cache;
    fi

    extra_volumes="--volume $CACHE_FOLDER:/composer_cache" rundocker  "$@" --verbose 
}

composer "$@"
