#!/bin/bash

rundocker () {
    tty=
    tty -s && tty=--tty

    docker run \
        $tty \
        --interactive \
        --rm \
        \
        --user $(id -u):$(id -g) \
        --volume /etc/passwd:/etc/passwd:ro \
        --volume /etc/group:/etc/group:ro \
        \
        --volume $(pwd):/app \
        \
        --volume $(dirname $SSH_AUTH_SOCK):$(dirname $SSH_AUTH_SOCK) \
        --env SSH_AUTH_SOCK=$SSH_AUTH_SOCK \
        ${extra_volumes} \
        ${extra_envars} \
        \
        ${DOCKER_IMAGE} "$@"
}